name: yaru_window_linux
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: yaru_window
    platforms:
      linux:
        pluginClass: YaruWindowLinuxPlugin
