name: yaru_window
description: WIP
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  yaru_window_linux:
    path: packages/yaru_window_linux ### TODO
  yaru_window_manager:
    path: packages/yaru_window_manager ### TODO
  yaru_window_platform_interface:
    path: packages/yaru_window_platform_interface ### TODO

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        default_package: yaru_window_linux
      macos:
        default_package: yaru_window_manager
      windows:
        default_package: yaru_window_manager
