name: yaru_window_web
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  yaru_window_platform_interface:
    path: ../yaru_window_platform_interface ### TODO

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: yaru_window
    platforms:
      web:
        pluginClass: YaruWebWindow
        fileName: src/web_window.dart
