name: yaru_window_manager
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.0
  yaru_window_platform_interface:
    path: ../yaru_window_platform_interface ### TODO

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: yaru_window
    platforms:
      macos:
        dartPluginClass: YaruWindowManager
      windows:
        dartPluginClass: YaruWindowManager
